
package com.example.myapplication;

public class DegiskenDegistirme {
    public static void main(String[] args) {
        String ilce = "İstanbul";
        String kita = "Asya";
        String faks = "+90 123 456 7890";
        String postaKodu = "34000";
        String instaAdresi = "@ornek_instagram";
        String calistiginBolum = "Muhasebe";
        int urunMiktari = 100;
        String musteriSoyadi = "Yılmaz";
        double odemeMiktari = 500.50;
        String dogumTarihi = "01/01/1990";
        double borc = 1000.00;
        String medeniHal = "Evli";
        String videoYorum = "Harika bir video!";
        double urunFiyati = 49.99;
        String yemekAdi = "Pizza";
        double boylam = 41.005;
        double enlem = 28.976;
        int daireSayisi = 5;
        double zamMiktari = 0.10;
        String basimTarihi = "15/10/2023";
        String dergiAdi = "Bilim Dünyası";
        String telefonModeli = "Samsung Galaxy S21";
        int satilanMiktar = 50;
        double eftMiktari = 750.25;
        String odemeSaati = "14:30";
        String sirket = "Örnek Şirket A.Ş.";
        String videoAdi = "örnek_video.mp4";
        int muzikSuresi = 180;
        double mekanPuani = 4.5;
        String dosyaAdi = "dosya.docx";
        String resimFormati = "JPEG";
        String renk = "Mavi";
        String renkKodu = "#0000FF";
        String bilgisayarModeli = "HP Envy x360";
        double ekranBoyutu = 15.6;
        int kullanimSuresi = 120;
        String faturaTarihi = "01/10/2023";
        String kuponKodu = "KUPON123";
        String kuponSuresi = "31/12/2023";
        String kargoTakipNo = "KRG123456";
        int kullanilanDakika = 300;
        String otobusHatti = "M2";
        String mahalleAdi = "Örnek Mahalle";
        String yolculukCikisTarihi = "20/11/2023";
        String odemeGunu = "05/11/2023";
        String etkinlikGunu = "15/12/2023";
        double basinca = 1013.25;


        System.out.println("İlçe: "+ilce);
        System.out.println("Kıta: "+kita);
        System.out.println("Faks: "+faks);
        System.out.println("Posta Kodu: "+postaKodu);
        System.out.println("Instagram Adresi: "+instaAdresi);
        System.out.println("Çalıştığınız Bölüm: "+calistiginBolum);
        System.out.println("Ürün Miktarı: "+urunMiktari);
        System.out.println("Müşteri Soyadı: "+musteriSoyadi);
        System.out.println("Ödeme Miktarı: "+odemeMiktari);
        System.out.println("Doğum Tarihi: "+dogumTarihi);
        System.out.println("Borç: "+borc);
        System.out.println("Medeni Hal: "+medeniHal);
        System.out.println("Video Yorumu: "+videoYorum);
        System.out.println("Ürün Fiyatı: "+urunFiyati);
        System.out.println("Yemek Adı: "+yemekAdi);
        System.out.println("Boylam: "+boylam);
        System.out.println("Enlem: "+enlem);
        System.out.println("Daire Sayısı: "+daireSayisi);
        System.out.println("Zam Miktarı: "+zamMiktari);
        System.out.println("Basım Tarihi: "+basimTarihi);
        System.out.println("Dergi Adı: "+dergiAdi);
        System.out.println("Telefon Modeli: "+telefonModeli);
        System.out.println("Satılan Miktar: "+satilanMiktar);
        System.out.println("EFT Miktarı: "+eftMiktari);
        System.out.println("Ödeme Saati: "+odemeSaati);
        System.out.println("Şirket: "+sirket);
        System.out.println("Video Adı: "+videoAdi);
        System.out.println("Müzik Süresi: "+muzikSuresi);
        System.out.println("Mekan Puanı: "+mekanPuani);
        System.out.println("Dosya Adı: "+dosyaAdi);
        System.out.println("Resim Formatı: "+resimFormati);
        System.out.println("Renk: "+renk);
        System.out.println("Renk Kodu: "+renkKodu);
        System.out.println("Bilgisayar Modeli: "+bilgisayarModeli);
        System.out.println("Ekran Boyutu: "+ekranBoyutu);
        System.out.println("Kullanım Süresi: "+kullanimSuresi);
        System.out.println("Fatura Tarihi: "+faturaTarihi);
        System.out.println("Kupon Kodu: "+kuponKodu);
        System.out.println("Kupon Süresi: "+kuponSuresi);
        System.out.println("Kargo Takip No: "+kargoTakipNo);
        System.out.println("Kullanılan Dakika: "+kullanilanDakika);
        System.out.println("Otobüs Hattı: "+otobusHatti);
        System.out.println("Mahalle Adı: "+mahalleAdi);
        System.out.println("Yolculuk Çıkış Tarihi: "+yolculukCikisTarihi);
        System.out.println("Ödeme Günü: "+odemeGunu);
        System.out.println("Etkinlik Günü: "+etkinlikGunu);
        System.out.println("Basınç: "+basinca);
    }
}